<a href="https://colab.research.google.com/github/mailtotapasishah-cloud/Ml_LAB_2026-27/blob/main/excelexample1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
df=pd.read_excel("/content/Technological-Products-Sample-Data.xlsx")

In [6]:
df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,NaN,Excel Sample Data,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Technological Products Data,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Brand,Device,Model,Country of Origin,Date of Release,Price (USD)

In [7]:
df.tail()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
30,NaN,Dell,UltraSharp,U2720Q,China,2020-12-25 00:00:00,499
31,NaN,HP,Elite,Dragonfly,United States,2021-06-28 00:00:00,1799
32,NaN,Lenovo,Legion,7i,China,2021-04-05 00:00:00,1499
33,NaN,Asus,TUF,Gaming A15,Taiwan,2021-03-20 00:00:00,1199
34,NaN,Acer,Aspire,5,Taiwan,2021-01-30 00:00:00,599

In [8]:
df.describe()

       Unnamed: 0
count         0.0
mean          NaN
std           NaN
min           NaN
25%           NaN
50%           NaN
75%           NaN
max           NaN

In [14]:
df.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6'],
      dtype='object')