<a href="https://colab.research.google.com/github/mailtotapasishah-cloud/Ml_LAB_2026-27/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


**Introduction to Pandas**

Pandas is an open-source software library written for the Python programming language, primarily used for data manipulation and analysis. It provides powerful and flexible data structures designed to make working with tabular and time-series data both easy and intuitive.

**Key features and functionalities of Pandas include: Data Structures:**

Pandas introduces two primary data structures:

**Series:** A one-dimensional labeled array capable of holding any data type. It can be thought of as a single column in a spreadsheet.

**DataFrame:** A two-dimensional labeled data structure with columns of potentially different data types. It is similar to a spreadsheet or SQL table, providing a powerful way to represent and manipulate tabular data.

**What is pandas used for?**

pandas is used throughout the data analysis workflow. With pandas, you can:

1.Import datasets from databases, spreadsheets, comma-separated values (CSV) files, and more. 2.Clean datasets, for example, by dealing with missing values. 3.Tidy datasets by reshaping their structure into a suitable format for analysis. 4.Aggregate data by calculating summary statistics such as the mean of columns, correlation between them, and more. 5.Visualize datasets and uncover insights.

**Importing data in pandas**

In [1]:
import pandas as pd

**Importing CSV files**

Use **read_csv()** with the path to the CSV file to read a comma-separated values file

In [2]:
df=pd.read_csv("/content/sample_data/california_housing_train.csv")

In [3]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [4]:
df.tail()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [5]:
df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000
mean,-119.562108,35.625225,28.589353,2643.664412,539.410824,1429.573941,501.221941,3.883578,207300.912353
std,2.005166,2.137340,12.586937,2179.947071,421.499452,1147.852959,384.520841,1.908157,115983.764387
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.790000,33.930000,18.000000,1462.000000,297.000000,790.000000,282.000000,2.566375,119400.000000
50%,-118.490000,34.250000,29.000000,2127.000000,434.000000,1167.000000,409.000000,3.544600,180400.000000
75%,-118.000000,37.720000,37.000000,3151.250000,648.250000,1721.000000,605.250000,4.767000,265000.000000
max,-114.310000,41.950000,52.000000,37937.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [6]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

**Importing text files**

In [7]:
df1=pd.read_csv("/content/archive (1).zip")

In [8]:
df1.head()

,student_id,age,gender,academic_level,study_hours,self_study_hours,online_classes_hours,social_media_hours,gaming_hours,sleep_hours,...,exercise_minutes,caffeine_intake_mg,part_time_job,upcoming_deadline,internet_quality,mental_health_score,focus_index,burnout_level,productivity_score,exam_score
0,1,23,Female,Postgraduate,1.72,4.53,1.80,2.01,1.50,7.05,...,75,38,No,No,Average,53.15,11.80,23.19,10.51,45.10
1,2,17,Other,Undergraduate,6.03,4.33,0.21,0.08,4.06,7.55,...,61,95,Yes,Yes,Excellent,14.83,21.30,9.24,57.73,9.91
2,3,20,Male,High School,1.64,2.07,2.07,3.16,2.78,5.09,...,91,23,No,No,Poor,85.34,56.77,33.17,22.91,29.23
3,4,20,Male,Undergraduate,7.36,3.79,2.92,1.50,4.66,5.59,...,63,254,No,No,Good,53.32,64.19,97.22,5.41,76.84
4,5,19,Female,Undergraduate,4.23,3.30,2.73,4.46,1.73,8.94,...,95,55,No,No,Poor,92.45,44.86,23.54,38.76,74.16

In [9]:
df1.tail()

,student_id,age,gender,academic_level,study_hours,self_study_hours,online_classes_hours,social_media_hours,gaming_hours,sleep_hours,...,exercise_minutes,caffeine_intake_mg,part_time_job,upcoming_deadline,internet_quality,mental_health_score,focus_index,burnout_level,productivity_score,exam_score
4995,4996,17,Male,Undergraduate,0.60,5.08,0.13,0.94,1.23,8.97,...,37,168,Yes,No,Poor,1.61,78.89,80.74,13.27,48.84
4996,4997,24,Male,High School,3.11,0.57,4.06,2.11,4.49,5.75,...,55,3,Yes,No,Poor,68.00,76.62,13.24,37.32,55.38
4997,4998,24,Female,Undergraduate,3.89,3.27,0.25,0.87,0.00,7.92,...,71,393,No,Yes,Average,74.94,17.24,57.52,3.06,11.56
4998,4999,24,Female,Undergraduate,3.41,3.06,3.43,2.17,1.79,4.78,...,16,309,No,No,Poor,60.68,97.12,54.39,31.61,61.08
4999,5000,24,Male,Undergraduate,0.89,2.78,0.82,2.28,0.98,8.90,...,76,107,Yes,Yes,Poor,31.24,23.35,34.32,32.05,19.59

In [11]:
df1.describe()

,student_id,age,study_hours,self_study_hours,online_classes_hours,social_media_hours,gaming_hours,sleep_hours,screen_time_hours,exercise_minutes,caffeine_intake_mg,mental_health_score,focus_index,burnout_level,productivity_score,exam_score
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,2500.500000,21.028000,4.284760,3.240326,2.488798,2.961974,2.484328,6.494074,6.065760,58.612800,198.039400,49.809352,50.236034,50.022450,50.105014,49.673066
std,1443.520003,2.593407,2.174137,1.595372,1.456146,1.743344,1.444887,1.420291,2.312687,34.520319,115.246759,29.181085,28.725337,28.527505,28.754482,29.088302
min,1.000000,17.000000,0.500000,0.500000,0.000000,0.000000,0.000000,4.000000,2.000000,0.000000,0.000000,0.010000,0.020000,0.020000,0.010000,0.040000
25%,1250.750000,19.000000,2.430000,1.840000,1.230000,1.440000,1.240000,5.280000,4.040000,29.000000,98.000000,24.542500,25.215000,25.652500,25.257500,23.727500
50%,2500.500000,21.000000,4.310000,3.250000,2.500000,2.980000,2.470000,6.510000,6.130000,59.000000,196.000000,49.545000,50.380000,49.705000,50.650000,49.910000
75%,3750.250000,23.000000,6.170000,4.610000,3.780000,4.470000,3.760000,7.690000,8.060000,88.000000,298.000000,75.212500,74.885000,74.715000,74.375000,75.070000
max,5000.000000,25.000000,8.000000,6.000000,5.000000,6.000000,5.000000,9.000000,10.000000,119.000000,399.000000,99.950000,99.990000,99.990000,99.970000,100.000000

In [12]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   student_id            5000 non-null   int64
 1   age                   5000 non-null   int64
 2   gender                5000 non-null   object
 3   academic_level        5000 non-null   object
 4   study_hours           5000 non-null   float64
 5   self_study_hours      5000 non-null   float64
 6   online_classes_hours  5000 non-null   float64
 7   social_media_hours    5000 non-null   float64
 8   gaming_hours          5000 non-null   float64
 9   sleep_hours           5000 non-null   float64
 10  screen_time_hours     5000 non-null   float64
 11  exercise_minutes      5000 non-null   int64
 12  caffeine_intake_mg    5000 non-null   int64
 13  part_time_job         5000 non-null   object
 14  upcoming_deadline     5000 non-null   object
 15  internet_quality      5000 non-null   object
 16  mental_health_score   5000 non-null   float64
 17  focus_index           5000 non-null   float64
 18  burnout_level         5000 non-null   float64
 19  productivity_score    5000 non-null   float64
 20  exam_score            5000 non-null   float64
dtypes: float64(12), int64(4), object(5)
memory usage: 820.4+ KB

In [13]:
df1.sum()

student_id                                                       12502500
age                                                                105140
gender                  FemaleOtherMaleMaleFemaleOtherMaleMaleOtherOth...
academic_level          PostgraduateUndergraduateHigh SchoolUndergradu...
study_hours                                                       21423.8
self_study_hours                                                 16201.63
online_classes_hours                                             12443.99
social_media_hours                                               14809.87
gaming_hours                                                     12421.64
sleep_hours                                                      32470.37
screen_time_hours                                                 30328.8
exercise_minutes                                                   293064
caffeine_intake_mg                                                 990197
part_time_job           NoYesNoNoNoYesYesYesNoYesYesYesNoYesNoYesYesYe...
upcoming_deadline       NoYesNoNoNoYesNoNoNoYesYesYesYesYesNoYesYesYes...
internet_quality        AverageExcellentPoorGoodPoorGoodGoodPoorAverag...
mental_health_score                                             249046.76
focus_index                                                     251180.17
burnout_level                                                   250112.25
productivity_score                                              250525.07
exam_score                                                      248365.33
dtype: object

In [14]:
df1.columns

Index(['student_id', 'age', 'gender', 'academic_level', 'study_hours',
       'self_study_hours', 'online_classes_hours', 'social_media_hours',
       'gaming_hours', 'sleep_hours', 'screen_time_hours', 'exercise_minutes',
       'caffeine_intake_mg', 'part_time_job', 'upcoming_deadline',
       'internet_quality', 'mental_health_score', 'focus_index',
       'burnout_level', 'productivity_score', 'exam_score'],
      dtype='object')